# Generated by Django 4.2 on 2024-03-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profesores',
            new_name='prof',
        ),
    ]
