# Generated by Django 4.2 on 2024-03-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0002_rename_profesores_prof'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estudiantes',
            new_name='estu',
        ),
    ]
