# Generated by Django 4.2 on 2024-03-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcolegio', '0003_rename_estudiantes_estu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='materias',
            new_name='mate',
        ),
    ]
